services:
  frontend:
    build:
      context: ./apps/frontend
    container_name: opennotify-frontend
    restart: unless-stopped
    ports:
      - "3003:3000"
    env_file:
      - ./apps/frontend/.env.local
    environment:
      - MONOLITH_API_URL=http://opennotify-backend:3004
    networks:
      - opennotify-net

  backend:
    build:
      context: ./apps/backend
    container_name: opennotify-backend
    restart: unless-stopped
    ports:
      - "3004:3001"
    env_file:
      - ./apps/backend/.env
    networks:
      - opennotify-net

networks:
  opennotify-net:
    driver: bridge
