services:
  frontend:
    build:
      context: ./apps/frontend
      args:
        - NEXT_PUBLIC_API_URL=http://k15-server:3004
    restart: unless-stopped
    ports:
      - "3003:3000"
    env_file:
      - ./apps/frontend/.env
    environment:
      - MONOLITH_API_URL=http://backend:3001
    networks:
      - app-net

  backend:
    build:
      context: ./apps/backend
    restart: unless-stopped
    ports:
      - "3004:3001"
    env_file:
      - ./apps/backend/.env
    networks:
      - app-net
      - shared-net

networks:
  app-net:
    driver: bridge
  shared-net:
    external: true